name: Create Ubuntu VPS

on:
  workflow_dispatch:

jobs:
  create-vm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Launch Ubuntu EC2
      run: |
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id ami-0dba2cb6798deb6d8 \
          --count 1 \
          --instance-type t2.micro \
          --key-name my-ssh-key \
          --query 'Instances[0].InstanceId' \
          --output text)
        echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

        PUBLIC_IP=$(aws ec2 describe-instances \
          --instance-ids $INSTANCE_ID \
          --query 'Reservations[0].Instances[0].PublicIpAddress' \
          --output text)
        echo "VPS_PUBLIC_IP=$PUBLIC_IP"
        echo "Your Ubuntu VPS is ready! Connect with PuTTY at IP: $PUBLIC_IP"
