name: Create Ubuntu VPS on Oracle Cloud

on:
  workflow_dispatch:

jobs:
  create-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install OCI CLI (non-interactive)
        run: |
          bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" -- --accept-all-defaults
          echo "export PATH=$PATH:$HOME/bin" >> $GITHUB_ENV
          export PATH=$PATH:$HOME/bin   # make it available in this step

      - name: Configure OCI CLI
        run: |
          mkdir -p $HOME/.oci
          echo "[DEFAULT]" > $HOME/.oci/config
          echo "user=${{ secrets.OCI_USER_OCID }}" >> $HOME/.oci/config
          echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> $HOME/.oci/config
          echo "key_file=$HOME/.oci/oci_api_key.pem" >> $HOME/.oci/config
          echo "tenancy=${{ secrets.OCI_TENANCY_OCID }}" >> $HOME/.oci/config
          echo "region=${{ secrets.OCI_REGION }}" >> $HOME/.oci/config
          echo "${{ secrets.OCI_PRIVATE_KEY }}" | base64 --decode > $HOME/.oci/oci_api_key.pem
          chmod 600 $HOME/.oci/oci_api_key.pem
          export PATH=$PATH:$HOME/bin   # ensure oci command is available

      - name: Create Ubuntu VM
        run: |
          export PATH=$PATH:$HOME/bin   # ensure oci command is available
          echo "Launching Ubuntu VM..."
          INSTANCE_OCID=$(oci compute instance launch \
            --compartment-id ${{ secrets.OCI_TENANCY_OCID }} \
            --availability-domain "Uocm:PHX-AD-1" \
            --shape "VM.Standard.E2.1.Micro" \
            --display-name "UbuntuVPS" \
            --image-id "ocid1.image.oc1.phx.<ubuntu_image_ocid>" \
            --ssh-authorized-keys-file $HOME/.ssh/id_rsa.pub \
            --query 'data.id' \
            --raw-output)
          echo "Instance OCID: $INSTANCE_OCID"

          PUBLIC_IP=$(oci compute instance list-vnics --instance-id $INSTANCE_OCID \
            --query 'data[0]."public-ip"' --raw-output)
          echo "✅ Your Ubuntu VPS Public IP: $PUBLIC_IP"
